language: node_js

node_js:
  - 7.0
  - 7.1
  - 7.2

install:
  - npm install
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

before_deploy:
  - npm run build
  - npm run cleanup

sudo: false

deploy:
  provider: heroku
  all_branches: true
  skip_cleanup: true
  api_key:
    secure: QYdYWMdWGZKckMKG413BpuEwkltoeTea7eR0peYitwkePPnclLDY3xKV6WoNIhAlJ/QzgpqsJL6bcd0BnJA449YtcHwqykeGb8JvYfwTo7hmcCVUie1AwZoXCmszVdEfE/4IiOX38Vx3Egvj81mfNopgEkdyb+0uAth35ow/1hw=
  app: freedraw
  on:
    repo: Wildhoney/Leaflet.FreeDraw

addons:
  apt:
    packages:
      - xvfb
