language: node_js

node_js:
  - 7.0
  - 7.1
  - 7.2

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_deploy:
  - npm run build
  - npm run cleanup

sudo: false

deploy:
  provider: heroku
  all_branches: true
  skip_cleanup: true
  api_key:
    secure: QYdYWMdWGZKckMKG413BpuEwkltoeTea7eR0peYitwkePPnclLDY3xKV6WoNIhAlJ/QzgpqsJL6bcd0BnJA449YtcHwqykeGb8JvYfwTo7hmcCVUie1AwZoXCmszVdEfE/4IiOX38Vx3Egvj81mfNopgEkdyb+0uAth35ow/1hw=
  app: freedraw
  on:
    repo: Wildhoney/Leaflet.FreeDraw