language: node_js

node_js:
  - '0.10'
  - '0.11'

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm install
  - bower install
  - grunt test

deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: dpIofJxARTkgAch2Ljo/+ITMxAairaFqAHEOcdrv0rxHeQZW1VUmW0KMzMuB0Tihxg173yK4Ogy1JeBvCt2PkzmEfkuN0/ELdt1uuLK+Rcup86VY8AOIzREBJHtuYxOpVjNcC8K99uswFmNerXNHbZmd0T3lA6kQdLRaf06eMKU=
  app: freedraw
  on:
    repo: Wildhoney/Leaflet.FreeDraw
