language: node_js
node_js: stable

install:
  - npm install
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

before_deploy:
  - npm run build
  - npm run cleanup

sudo: false

addons:
  apt:
    packages:
      - xvfb

deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: K973JhR57s624f0zC7GrFMElDGE9p3/iEDf+cZTmx/ZhcSC/JYoU4rID51wgTUwKh+0LoD/aKc8G/D347r4QjpO1MW7ekNlNIohyv8DToTx3CeWDAAd5r+WoX/0VSmtxR72f7EMvuq07rH1l8ck+Ot9Gzk5Rtss3W2LSWc0xYBQ=
  app: freedraw
  on:
    repo: Wildhoney/Leaflet.FreeDraw
